import { MigrationInterface, QueryRunner } from 'typeorm';

const CREATE_COMMENTS_INDEX =
  'CREATE INDEX "idx_comments_article_created_id" ON "comments" ("article_id" ASC, "created_at" ASC, "id" ASC)';
const DROP_COMMENTS_TABLE = 'DROP TABLE IF EXISTS "comments"';

export class CreateComments1710000005000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'CREATE TABLE "comments" (' +
        '"id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "pk_comments" PRIMARY KEY, ' +
        '"article_id" uuid NOT NULL, ' +
        '"author_id" uuid NOT NULL, ' +
        '"body" text NOT NULL, ' +
        '"created_at" timestamptz NOT NULL DEFAULT now(), ' +
        '"updated_at" timestamptz NOT NULL DEFAULT now(), ' +
        'CONSTRAINT "fk_comments_article" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE CASCADE, ' +
        'CONSTRAINT "fk_comments_author" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE)',
    );
    await queryRunner.query(CREATE_COMMENTS_INDEX);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(DROP_COMMENTS_TABLE);
  }
}
