import { describe, expect, it, vi } from 'vitest';

import { CreateComments1710000005000 } from '../../../../src/database/migrations/1710000005000-create-comments.js';

describe('CreateComments1710000005000', () => {
  it('creates an integer comment table with cascading references and list index', async () => {
    const query = vi.fn().mockResolvedValue(undefined);

    await new CreateComments1710000005000().up({ query } as never);

    expect(query).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining('CREATE TABLE "comments"'),
    );
    expect(query).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining('"id" integer GENERATED BY DEFAULT AS IDENTITY'),
    );
    expect(query).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining('"body" text NOT NULL'),
    );
    expect(query).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining(
        'FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE CASCADE',
      ),
    );
    expect(query).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining(
        'FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE',
      ),
    );
    expect(query).toHaveBeenNthCalledWith(
      2,
      'CREATE INDEX "idx_comments_article_created_id" ON "comments" ("article_id" ASC, "created_at" ASC, "id" ASC)',
    );
  });

  it('removes the comment table on rollback', async () => {
    const query = vi.fn().mockResolvedValue(undefined);

    await new CreateComments1710000005000().down({ query } as never);

    expect(query).toHaveBeenCalledWith('DROP TABLE IF EXISTS "comments"');
  });
});
